[package]
name = "adtensor"
version = "0.0.3"
authors = ["Charles Earp <charles.r.earp@gmail.com>"]
edition = "2018"
description = "Graph based machine learning libray built on ndarray."
license = "GPL-3.0"
repository = "https://github.com/charles-r-earp/adtensor"
keywords = ["Auto", "Learning", "ndarray", "Tensor"]

[dependencies]
rand = "0.6.5"
matrixmultiply = "0.2.2"
arrayvec = "0.4.10"
smallvec = "0.6.9"

[profile.dev]
opt-level = 0

[profile.bench]
opt-level = 3

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench_tensor_dot"
harness = false
