[package]
name = "adtensor"
version = "0.0.1"
authors = ["Charles Earp <charles.r.earp@gmail.com>"]
edition = "2018"
description = "Machine learning library with auto differentiation of arbitrary dimensional stack tensors."
license = "GPL-3.0"

[dependencies]
generic-array = "0.12.0"
typenum = "1.10.0"
typename = "0.1.0"
